### ISSUE TITLE
Example for Swift

### ISSUE THREAD

**Issue by Danielthenew** [ThabreshVivid/TYDirectionFinder#1]
Give it this example only in Objective-C or also in Swift?

**Comment by ThabreshVivid** [comment]
No its only for Objective C

**Comment by ThabreshVivid** [comment]
@Danielthenew i will update you soon

**Comment by ThabreshVivid** [comment]
@Danielthenew https://github.com/ThabreshVivid/TYDirectionSwift check this TYDirectionSwift its written in swift language...Happi Coding
